apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ur4oezgls-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ur4oezgls-go 
  name: ur4oezgls-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ur4oezgls-go 
